### ISSUE TITLE
[minor] game over actually missing

### ISSUE THREAD

**Issue by pirate486743186** [EasyRPG/RTP#22]
the website
https://easyrpg.org/rtp-replacement/progress/

says game over is done. But it's not present here...

**Comment by carstene1ns** [comment]
It is here: https://github.com/EasyRPG/TestGame/blob/master/TestGame-2000/GameOver/GameOver.png

We currently lack a way to have TestGame and RTP not duplicate assets.

**Comment by Ghabry** [comment]
iirc the problem with GameOver was that it looks beautiful but the author was unknown? (ping @fdelapena )

**Comment by fdelapena** [comment]
Yes, can't remember the author nickname, this was in the old Spanish language forums... maybe is ok to update the details in the website for now.

**Comment by pirate486743186** [comment]
hum.... did you guys knew, that copyright of fonts persist if used in images. Right?

**Comment by fdelapena** [comment]
> hum.... did you guys knew, that copyright of fonts persist if used in images. Right?

Well, that depends on countries. A new gameover design is welcome, based on SIL or other fonts with friendly licenses.

**Comment by ItsSchoko** [comment]
Any suggestions?
Something similar, maybe?

**Comment by Ghabry** [comment]
Solved by jetrotal:

![unknown](https://user-images.githubusercontent.com/1331889/166656079-cddd9858-dd7e-415f-99c7-66d9489f7ac3.png)

Not the same file due to licensing issues :)
